// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChcXYfedwgVwx6A-Vl28uUp4sorMSgdO4',
    appId: '1:257992251767:web:893b35915c6506a5c06972',
    messagingSenderId: '257992251767',
    projectId: 'abaya-designer-396ca',
    authDomain: 'abaya-designer-396ca.firebaseapp.com',
    storageBucket: 'abaya-designer-396ca.firebasestorage.app',
    measurementId: 'G-WHHZ61L993',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdIC9pfDvJ4f-IElfY2mGLOd4YsEouPyc',
    appId: '1:257992251767:android:725e19f013631028c06972',
    messagingSenderId: '257992251767',
    projectId: 'abaya-designer-396ca',
    storageBucket: 'abaya-designer-396ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmTRcdYsCH0Uwt6TPgQjSrmgZBGTT1QcE',
    appId: '1:257992251767:ios:766cc52f0e204578c06972',
    messagingSenderId: '257992251767',
    projectId: 'abaya-designer-396ca',
    storageBucket: 'abaya-designer-396ca.firebasestorage.app',
    iosBundleId: 'com.example.abayaDesigner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmTRcdYsCH0Uwt6TPgQjSrmgZBGTT1QcE',
    appId: '1:257992251767:ios:766cc52f0e204578c06972',
    messagingSenderId: '257992251767',
    projectId: 'abaya-designer-396ca',
    storageBucket: 'abaya-designer-396ca.firebasestorage.app',
    iosBundleId: 'com.example.abayaDesigner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChcXYfedwgVwx6A-Vl28uUp4sorMSgdO4',
    appId: '1:257992251767:web:111b75f17d5f89f9c06972',
    messagingSenderId: '257992251767',
    projectId: 'abaya-designer-396ca',
    authDomain: 'abaya-designer-396ca.firebaseapp.com',
    storageBucket: 'abaya-designer-396ca.firebasestorage.app',
    measurementId: 'G-2QYLEX56JK',
  );
}
